### PR TITLE
Added license to beginning of all c++ files.

### PR DESCRIPTION
**Pull request by jsallay**
I didn't add the license to the files in the bench directory because I believe that those were copied from elsewhere.  I also didn't add anything to the fbs file.  I can add something in those cases if desired.

### CODE REVIEW

**Comment by dkozel** [comment]
@jsallay Two thumbs up on adding the licenses using SPDX, but several temp binary files snuck into the commit.

**Comment by jsallay** [comment]
> @jsallay Two thumbs up on adding the licenses using SPDX, but several temp binary files snuck into the commit.
Good catch.  Fixed.

**Comment by dkozel** [comment]
Thanks. Also you've added `.github/workflows/build_and_test.yml` which is unrelated and looks like it's causing a CI error now.

**Comment by jsallay** [comment]
> Thanks. Also you've added `.github/workflows/build_and_test.yml` which is unrelated and looks like it's causing a CI error now.
The file was already there, but it wasn't working.  It looks like when it was split out from the main newsched, a few items like installing the flatbuffers compiler didn't get transferred over.  I'll open a new issue for @mormj to look at.

**Comment by mormj** [comment]
I've put flatc into the ci docker now, so the updates to build_and_test.yml can be removed from the PR and it should build fine.

**Comment by jsallay** [comment]
Thanks, I'll try it out tonight.

John

**Pull request merged**
